alter table ballot change comp entry int;
alter table changes change comp entry int;
alter table follow_comp change comp entry int;
alter table rating change comp entry int;
alter table strike change comp entry int;
alter table student_result change comp entry int;
alter table entry_student change comp entry int;
alter table chapter_circuit change league circuit int;
alter table due_payment change league circuit int;
alter table email change league circuit int;
alter table circuit_admin change league circuit int;
alter table circuit_chapter change league circuit int;
alter table news change league circuit int;
alter table region change league circuit int;
alter table site change league circuit int;
alter table concession_purchase change item concession int;
alter table rating change qual rating_tier int;
alter table rating_tier change qual_subset rating_subset int;
alter table changes rename to tourn_change;
alter table account drop change_deadline;
alter table account change change_timestamp password_timestamp datetime;
