#!/bin/bash
ln -s /bin/chmod /usr/bin/chmod > /dev/null 2>&1
rsync -avzru amazon@azuen.net:/home/palmer/Dropbox/Tech/Backup/files /www/
rsync -avzru /www/files amazon@azuen.net:/home/palmer/Dropbox/Tech/Backup/

