alter table ballot drop hangout_admin;
alter table category drop pattern;
alter table change_log change created created_at datetime;
alter table change_log change type tag varchar(63);
alter table ballot modify chair bool after audit;
alter table chapter drop self_prefs;
alter table chapter drop nces;
alter table chapter drop ipeds;
alter table chapter drop ceeb;
alter table chapter drop coaches;
drop table circuit_membership;
alter table chapter_setting drop created_at;
drop table diocese;
alter table district drop chair;
alter table judge drop tmp;
alter table judge drop score;
alter table login drop source;
alter table login drop password;
rename nsda_event_category TO nsda_category;
alter table panel drop started;
alter table panel drop flip;
alter table panel drop flip_at;
alter table panel drop flip_status;
alter table panel drop g_event;
alter table panel drop room_ext_id;
alter table panel drop invites_sent;
alter table person drop gender;
alter table person drop diversity;
drop table qualifier;
alter table rating drop sheet;
drop table region_fine;
alter table result drop honor;
alter table result drop honor_site;
alter table room drop building;
alter table round drop post_results;
alter table round change created created_at datetime;
alter table rpool_setting drop type;
alter table score drop cat_id;
alter table score drop tiebreak;
alter table session drop tourn;
alter table session drop event;
alter table session drop weekend;
alter table session drop category;
alter table student modify gender char(4);
drop table stats;
alter table student_setting drop created_at;
alter table school_setting drop chapter;
alter table weekend modify state char(4) after end;
update weekend set city="Crescenta Valley High School" where id="70";
alter table weekend modify city varchar(127) after end;
