alter table ballot drop hangout_admin;
alter table category drop pattern;
alter table change_log change created created_at datetime;
alter table change_log change type tag varchar(63);
alter table ballot modify chair bool after audit;
alter table chapter drop self_prefs;
alter table chapter drop nces;
alter table chapter drop ceeb;
alter table chapter drop coaches;
drop table circuit_membership;
alter table chapter_setting drop created_at;
drop table diocese;
alter table district drop chair;
alter table judge drop tmp;
alter table judge drop score;
alter table login drop source;
alter table login drop password;
rename nsda_event_category TO nsda_category;
alter table panel drop started;
alter table panel drop flip;
alter table panel drop flip_at;
alter table panel drop flip_status;
alter table panel drop g_event;
alter table panel drop room_ext_id;
alter table panel drop invites_sent;
alter table person drop gender;
alter table person drop diversity;
drop table qualifier;


