FROM node:18

WORKDIR /usr/local

COPY api/package*.json .
RUN npm install pm2 -g
RUN npm ci
ENV PATH=/usr/local/node_modules/.bin:$PATH

WORKDIR /usr/local/app
COPY api .
RUN cp config/config.js.sample config/config.js

EXPOSE 10010