#!/bin/bash

hostname=`hostname -s`

#dbIp=`docker inspect $(docker ps -f=name=tabroom-docker_db -q) | grep -i "ip.*[12]*\.[0-9]*" | sed -e 's/^  *//g' -e 's/[",]//g' -e 's/[a-zA-Z: ]//g'`

#why yes, I'm too lazy to look up how arrays work in bash

prodserver='athena'
prodserver1='castor'
prodserver2='freyr'
prodserver3='geb'

if [[ ${hostname} != ${prodserver} ]]; then
if [[ ${hostname} != ${prodserver1} ]]; then
if [[ ${hostname} != ${prodserver2} ]]; then
if [[ ${hostname} != ${prodserver3} ]]; then

	echo "Removing old data dump"
	rm /tmp/tabroom.sql
	rm /tmp/tabroom.sql.bz2 

	echo "Accessing latest data dump"
	s3cmd get s3://tabroom-db/latest/tabroom.sql.bz2  /tmp/tabroom.sql.bz2

	echo "Decompressing data dump"
	pv /tmp/tabroom.sql.bz2 | bzip2 -d > /tmp/tabroom.sql

	echo "Dropping old database"
	docker exec -u root $(docker ps -f=name=tabroom-docker_db -q) /usr/bin/mysql -u root -proot -e "drop database if exists tabroom;"

	echo "Creating new blank database"
    docker exec -u root $(docker ps -f=name=tabroom-docker_db -q) /usr/bin/mysqladmin -u root -proot create tabroom

	echo "Loading datafile"
	pv /www/tabroom/doc/docker/beforedatabasesync.sql | docker exec -i $(docker ps -f=name=tabroom-docker_db -q) /usr/bin/mysql -u root -proot tabroom
	pv tabroom.sql | docker exec -i $(docker ps -f=name=tabroom-docker_db -q) /usr/bin/mysql -u root -proot tabroom
  	pv /www/tabroom/doc/docker/afterdatabasesync.sql | docker exec -i $(docker ps -f=name=tabroom-docker_db -q) /usr/bin/mysql -u root -proot tabroom

	echo "Loading tables with external views on Tabroom"
  	pv /www/tabroom/doc/convert/calendar.sql | docker exec -i $(docker ps -f=name=tabroom-docker_db -q) /usr/bin/mysql -u root -proot tabroom

    echo "new stuffs (this may report error)"
  	pv /www/tabroom/doc/convert_session.sql | docker exec -i $(docker ps -f=name=tabroom-docker_db -q) /usr/bin/mysql -u root -proot tabroom

	echo "All set!"
fi
fi
fi
fi

