#!/bin/bash

hostname=`hostname -s`
prodserver='hera'

if [[ ${hostname} != ${prodserver} ]]; then

	rm /tmp/tabroom.sql

	echo "Accessing latest data dump"

	s3cmd get s3://tabroom-db/latest/tabroom.sql.bz2  /tmp/tabroom.sql.bz2

	echo "Decompressing data dump"

	bunzip2 /tmp/tabroom.sql.bz2

	echo "Dropping old database"

	mysqladmin -u root -f drop tabroom_backup

	echo "Creating new blank database"

	mysqladmin -u root create tabroom_backup

	echo "Loading datafile"

	mysql -u root -f tabroom_backup < /tmp/tabroom.sql

	echo "Loading tables with external views on Tabroom"
	mysql -u root -f tabroom_backup < /www/backup.tabroom.com/doc/convert/calendar.sql

	echo "Setting up the node.js views"
	mysql -u root -f tabroom_backup < /www/backup.tabroom.com/doc/tabroom-api-view.sql

	echo "Removing data dump"
	rm /tmp/tabroom.sql

	echo "All set!"

fi

