#!/bin/bash

hostname=`hostname -s`
prodserver='hera'

if [[ ${hostname} != ${prodserver} ]]; then

	rm /tmp/tabroom.sql

	echo "Accessing latest data dump"

	s3cmd get s3://speechanddebate-latest/db/tabroom.sql.bz2  /tmp/tabroom.sql.bz2

	echo "Decompressing data dump"

	bunzip2 /tmp/tabroom.sql.bz2

	echo "Dropping old database"

	mysqladmin -u root -f drop tabroom_backup

	echo "Creating new blank database"

	mysqladmin -u root create tabroom_backup

	echo "Loading datafile"

	pv /tmp/tabroom.sql | mysql -u root -f tabroom_backup

	echo "Setting up the node.js views"
	mysql -u root -f tabroom_backup < /www/tabroom/doc/tabroom-api-view.sql

	echo "Removing data dump"
	rm /tmp/tabroom.sql

	echo "All set!"

fi

