#!/bin/bash

hostname=`hostname -s`
user="root";

# never run this on a production server, even on purpose.
# why yes, I am too lazy to look up how arrays work in bash

prodserver='tabroom-db'
prodserver1='tabroom-replica'

if [[ ${hostname} != ${prodserver} ]]; then
if [[ ${hostname} != ${prodserver1} ]]; then

	rm /tmp/tabroom.sql

	if [[ ${hostname} == "amun" ]]; then
		echo "Copying the latest database backup"
		cp /net/backups/database-hourlies/latest/tabroom.sql.bz2 /tmp/tabroom.sql.bz2
	else
		echo "Downloading latest database backup"
		aws s3 cp s3://nsda-backups/00-latest/tabroom.sql.bz2  /tmp/tabroom.sql.bz2
	fi

	echo "Decompressing backup data"
	bunzip2 /tmp/tabroom.sql.bz2

	echo "Deleting old tabroom database"
	mysqladmin -u ${user} -f drop tabroom

	echo "Creating new blank tabroom database"
	mysqladmin -u ${user} create tabroom

	echo "Loading datafile into new database"
	pv /tmp/tabroom.sql | mysql -u ${user} -f tabroom

	#echo "Loading tables with external views on Tabroom"
	#mysql -u ${user} -f tabroom < /www/tabroom/doc/convert/triggers.sql

	echo "Removing data dump"
	rm /tmp/tabroom.sql

	echo "All set!"
fi
fi
