#!/bin/bash

hostname=`hostname -s`

# why yes, I am too lazy to look up how arrays work in bash

prodserver='athena'
prodserver1='castor'
prodserver2='freyr'
prodserver3='geb'

if [[ ${hostname} != ${prodserver} ]]; then
if [[ ${hostname} != ${prodserver1} ]]; then
if [[ ${hostname} != ${prodserver2} ]]; then
if [[ ${hostname} != ${prodserver3} ]]; then

	rm /tmp/tabroom.sql

	echo "Accessing latest data dump"

	s3cmd get s3://tabroom-db/latest/tabroom.sql.bz2  /tmp/tabroom.sql.bz2

	echo "Decompressing data dump"

	bunzip2 /tmp/tabroom.sql.bz2

	echo "Dropping old database"

	mysqladmin -u root -f drop tabroom

	echo "Creating new blank database"

	mysqladmin -u root create tabroom

	echo "Loading datafile"

	pv /tmp/tabroom.sql | mysql -u root -f tabroom 

	echo "Loading tables with external views on Tabroom"
	mysql -u root -f tabroom < /www/tabroom/doc/convert/calendar.sql

	echo "Removing data dump"
	rm /tmp/tabroom.sql

	echo "All set!"

fi
fi
fi
fi
