#!/bin/bash

hostname=`hostname -s`
user="root";

if [[ "$1" != "" ]]; then
    database="$1"
else
	database="tabroom"
fi

# never run this on a production server, even on purpose. why yes, I am too
# lazy to look up how hash and arrays work in bash how did you know?

prodserver='tab-db'
prodserver1='tab-replica'

echo "Loading latest database backup into ${database} on ${hostname}"
echo "Start time is"
date

if [[ ${hostname} != ${prodserver} ]]; then
if [[ ${hostname} != ${prodserver1} ]]; then

	echo "Started at"
	date

	rm  -r /data/tmp/tabroom
	touch /www/tabroom/web/lib/nodb

	if [[ ${hostname} == "redwoods" ]]; then
		echo "Copying the latest database backup"
		cp -L /backup/tabroom/latest/tabroom.tar /data/tmp/tabroom.tar
	else
		echo "Downloading latest database backup"
		aws s3 cp s3://nsda-backups/00-latest/tabroom.tar  /data/tmp/tabroom.tar
	fi

	echo "Opening data archive"
	tar xvf /data/tmp/tabroom.tar -C /data/tmp/

	echo "Deleting old tabroom database"
	mysqladmin -u ${user} -f drop ${database}

	echo "Creating new blank tabroom database"
	mysqladmin -u ${user} create ${database}

	echo "Loading datafile into new database"
	myloader --directory /data/tmp/tabroom -v 4 --threads 32 --database ${database}

	echo "Removing data directory"
	rm /data/tmp/tabroom.tar
	rm  -r /data/tmp/tabroom
	rm /www/tabroom/web/lib/nodb

	echo "All set!"
	echo "Ended at"
	date
fi
fi
