#!/usr/bin/perl -w

my @prod_servers = ("tabroom-www1", "tabroom-www2");

foreach my $server (@prod_servers) {
	print "\n\nDEPLOYING TO ".$server."\n\n";
	my $result = system "ssh tabroom\@$server \"cd /www/tabroom; git pull\" ";
	print "\nRESULT IS $result\n\n";
	system "ssh tabroom\@$server \"cd /www/tabroom/api; npm install\" ";
	system "ssh tabroom\@$server \"sudo systemctl restart indexcards\" ";
}
