#!/usr/bin/perl -w

my @prod_servers = ("tabroom-www1", "tabroom-www2");

foreach my $server (@prod_servers) {
	print "\n\nDEPLOYING TO ".$server."\n\n";

	my $result = `ssh tabroom\@$server \"cd /www/tabroom; git pull 2>&1\" `;
	chomp $result;

	if ($result eq "Already up to date.") {
		print "No new code found. $server update done.\n";
	} else {
		print "New code found:\n";
		print $result;
		print "\n\nUpdating the Node API on $server\n";
		system "ssh tabroom\@$server \"cd /www/tabroom/api; npm install\" ";
		system "ssh tabroom\@$server \"sudo systemctl restart indexcards\" ";
	}
}
