#!/bin/bash

hostname=`hostname -s`

#why yes, I'm too lazy to look up how arrays work in bash

prodserver='athena'
prodserver1='castor'
prodserver2='freyr'
prodserver3='geb'

if [[ ${hostname} != ${prodserver} ]]; then
if [[ ${hostname} != ${prodserver1} ]]; then
if [[ ${hostname} != ${prodserver2} ]]; then
if [[ ${hostname} != ${prodserver3} ]]; then

	rm /tmp/nationals.sql

	echo "Accessing latest data dump"

	s3cmd get s3://speechanddebate-db/latest/nationals.sql.bz2  /tmp/nationals.sql.bz2

	echo "Decompressing data dump"

	bunzip2 /tmp/nationals.sql.bz2

	echo "Dropping old database"

	mysqladmin -u root -f drop nationals

	echo "Creating new blank database"

	mysqladmin -u root create nationals

	echo "Loading datafile"

	pv /tmp/nationals.sql | mysql -u root -f nationals 

	echo "Removing data dump"
	rm /tmp/nationals.sql

	echo "All set!"

fi
fi
fi
fi

