#!/usr/bin/perl -w

my $hostname=`hostname -s`;

chomp $hostname;

if ($hostname eq "abe" || $hostname eq "mihashi") {

	print "DEPLOYING MASON TO $hostname\n";
	my $result = `cd /www/tabroom; git pull`;
	print $result;
	print "\n";

	print "DEPLOYING INDEXCARDS to $hostname\n";
	$result = `cd /www/indexcards; git pull`;
	chomp $result;
	$result = lc($result);

	if ($result eq "already up to date.") {
		print "No NPM updates needed. $hostname update done.\n";
	} else {
		print "New code downloaded.  Updating the Node API\n";
		system "cd /www/indexcards; npm install";
	}

} else {

	print " DEPLOYING MASON to localhost";
	my $result = `ssh tabroom\@localhost \"cd /www/tabroom; git pull\"`;
	print $result;
	print "\n";

	print "DEPLOYING INDEXCARDS to $hostname\n";
	$result = `ssh tabroom\@localhost \"cd /www/indexcards; git pull\"`;
	chomp $result;
	$result = lc($result);

	if ($result eq "already up to date.") {
		print "No NPM updates needed.  Done.\n";
	} else {
		print "Updating the Node API\n";
		system "ssh tabroom\@localhost \"cd /www/indexcards; npm install\" ";
		system "ssh tabroom\@localhost \"sudo systemctl restart indexcards\" ";
	}
}
