#!/usr/bin/perl -w

my $hostname=`hostname -s`;

chomp $hostname;

print $hostname;

if ($hostname eq "thasalon" || $hostname eq "gotorget") {

	print " DEPLOYING TO $hostname";
	system "cd /www/tabroom; git pull";

} else {

	print " DEPLOYING TO localhost";
	system "ssh tabroom\@localhost \"cd /www/tabroom; git pull\" ";
	system "ssh tabroom\@localhost \"cd /www/tabroom/api; npm install\" ";
	system "ssh tabroom\@localhost \"sudo systemctl stop indexcards\" ";
	system "ssh tabroom\@localhost \"sudo systemctl start indexcards\" ";

}
