#!/usr/bin/perl -w

my $hostname=`hostname -s`;

chomp $hostname;

print $hostname;

if ($hostname eq "abe" || $hostname eq "mihashi") {

	print "DEPLOYING TO $hostname";
	system "cd /www/tabroom; git pull";

} else {

	print " DEPLOYING TO localhost";
	my $result = system "ssh tabroom\@localhost \"cd /www/tabroom; git pull\" ";

	print "\nRESULT IS $result\n\n";

	system "ssh tabroom\@localhost \"cd /www/tabroom/api; npm install\" ";
	system "ssh tabroom\@localhost \"sudo systemctl restart indexcards\" ";

}
