#!/usr/bin/perl -w

my @stage_servers = ("loki.tabroom.com");

foreach my $server (@stage_servers) { 
	print " DEPLOYING TO ".$server;
	system "ssh palmer\@$server \"cd /www/tabroom; git pull\" ";
	system "ssh palmer\@$server \"sudo service apache2 restart\"";
}

my @test_servers = ("azuen.net");

foreach my $server (@test_servers) { 
	print " DEPLOYING TO ".$server;
	system "ssh palmer\@$server \"cd /www/testing.tabroom.com; git pull\" ";
	system "ssh palmer\@$server \"sudo service testing restart\"";
}
