#!/bin/bash

hostname=`hostname -s`

# why yes, I am too lazy to look up how arrays work in bash
# never run this on a production server, even on purpose. 

sourcedir='/net/backups/database-binaries'
prodserver='athena'

if [[ ${hostname} == ${prodserver} ]]; then

	if [[ $1 == "daily" ]]; then 
		echo "Moving the previous daily copy";
		mv ${sourcedir}/daily-tabroom-1.tar.xz ${sourcedir}/daily-tabroom-2.tar.xz
		filename="daily-tabroom-1.tar.xz"
	else 
		echo "Moving the previous hourly copies";
		mv ${sourcedir}/hourly-tabroom-3.tar.xz ${sourcedir}/hourly-tabroom-4.tar.xz
		mv ${sourcedir}/hourly-tabroom-2.tar.xz ${sourcedir}/hourly-tabroom-3.tar.xz
		mv ${sourcedir}/hourly-tabroom-1.tar.xz ${sourcedir}/hourly-tabroom-2.tar.xz
		filename="hourly-tabroom-1.tar.xz"
	fi

	echo "Removing previous backup files"
	rm -r ${sourcedir}/latest-tabroom

	echo "Performing hotbackup"
	/usr/bin/xtrabackup --backup --databases="tabroom"
	/usr/bin/xtrabackup --prepare --export --databases="tabroom"

	echo "Compressing backup data"
	ssh osiris "cd /data/backups/database-binaries; tar cf - latest-tabroom | xz -z -3 - > ${sourcedir}/latest-tabroom.tar.xz"
	ssh osiris "cp ${sourcedir}/latest-tabroom.tar.xz ${sourcedir}/${filename}"
	echo "All set!"
fi

