#!/bin/bash

hostname=`hostname -s`

# why yes, I am too lazy to look up how arrays work in bash
# never run this on a production server, even on purpose. 

prodserver='athena'

if [[ ${hostname} == ${prodserver} ]]; then

	echo "Removing previous backup files"
	#rm -r /backups/latest-tabroom

	echo "Performing hotbackup"
	#/usr/bin/xtrabackup --backup --databases="tabroom"

	echo "Compressing backup data"
	cd /backups
	tar zcvf /home/s3/backups/latest-tabroom.tgz latest-tabroom

	echo "All set!"
fi
