#!/bin/bash

hostname=`hostname -s`
release=`lsb_release -rs`
user=`whoami`

target='16.04'

if [[ ${release} != ${target} ]]; then 
	echo "This method only works when running the same release as Athena, currently 16.04."
	echo "You're stuck with the old fashioned way; use database-sync instead"
	exit
fi

if [[ ${user} != "root" ]]; then 
	echo "You must be root for this script to work, not $user"
	exit
fi

filename="hourly-tabroom-1.tar.xz"

if [[ ${2} == "daily" ]]; then 
	if [[ ${1} == "2" ]]; then 
		filename="daily-tabroom-1.tar.xz"
	else
		filename="daily-tabroom-2.tar.xz"
	fi
else 
	
	if [[ ${1} == "2" ]]; then 
		filename="hourly-tabroom-2.tar.xz"
	fi
	if [[ ${1} == "3" ]]; then 
		filename="hourly-tabroom-3.tar.xz"
	fi
	if [[ ${1} == "4" ]]; then 
		filename="hourly-tabroom-4.tar.xz"
	fi
fi

# never run this on a production server, even on purpose.  why yes, I am too
# lazy to look up how arrays work in bash, why do you ask?

staging='loki'
prodserver='athena'
prodserver1='castor'
prodserver2='freyr'
prodserver3='geb'

if [[ ${hostname} != ${prodserver} ]]; then
if [[ ${hostname} != ${prodserver1} ]]; then
if [[ ${hostname} != ${prodserver2} ]]; then
if [[ ${hostname} != ${prodserver3} ]]; then

	rm /data/tmp/${filename}
	rm -r /data/tmp/latest-tabroom
	rm -r /var/lib/mysql/tabroom/*.exp
	rm -r /var/lib/mysql/tabroom/*.frm

	if [[ ${hostname} == ${staging} ]]; then
		echo "Copying latest database backup locally"
		cp /net/backups/database-binaries/${filename} /data/tmp
	else 
		echo "Downloading latest database backup"
		scp loki.tabroom.com:/home/s3/backups/${filename}  /data/tmp/${filename}
	fi

	echo "Decompressing downloaded backup data"
	tar Jxvf /data/tmp/${filename} -C /data/tmp

	echo "Deleting old tabroom database"
	service mysql restart
	mysqladmin -u root -f drop tabroom
	rm -r /var/lib/mysql/tabroom/*.*
	mysqladmin -u root -f drop tabroom

	echo "Reloading the Tabroom schema"
	mysqladmin -u root create tabroom
	pv /www/tabroom/doc/sql/tabroom-schema.sql | mysql -u root -f tabroom 

	echo "Discarding the tablespaces"
	pv /www/tabroom/doc/sql/drop-tablespaces.sql | mysql -u root -f tabroom 

	echo "Copying backup tablespaces to mysql"
	cp /data/tmp/latest-tabroom/tabroom/*.ibd /var/lib/mysql/tabroom/
	cp /data/tmp/latest-tabroom/tabroom/*.cfg /var/lib/mysql/tabroom/
	cp /data/tmp/latest-tabroom/tabroom/*.exp /var/lib/mysql/tabroom/

	chown -R mysql.mysql /var/lib/mysql/tabroom/

	echo "Importing the backup tablespaces"
	pv /www/tabroom/doc/sql/import-tablespaces.sql | mysql -u root -f tabroom 

	echo "Removing data dump"
	rm -r /var/lib/mysql/tabroom/*.exp
	rm -r /data/tmp/latest-tabroom
	rm /data/tmp/${filename}

	echo "All set!"
fi
fi
fi
fi
