#!/bin/bash

hostname=`hostname -s`

# why yes, I am too lazy to look up how arrays work in bash
# never run this on a production server, even on purpose. 

prodserver='athena'

if [[ ${hostname} == ${prodserver} ]]; then

	if [[ $1 == "daily" ]]; then 
		echo "Moving the previous daily copy";
		mv /home/s3/backups/daily-tabroom-1.tar.bz2 /home/s3/backups/daily-tabroom-2.tar.bz2
		filename="daily-tabroom-1.tar.bz2"
	else 
		echo "Moving the previous hourly copies";
		mv /home/s3/backups/hourly-tabroom-3.tar.bz2 /home/s3/backups/hourly-tabroom-4.tar.bz2
		mv /home/s3/backups/hourly-tabroom-2.tar.bz2 /home/s3/backups/hourly-tabroom-3.tar.bz2
		mv /home/s3/backups/hourly-tabroom-1.tar.bz2 /home/s3/backups/hourly-tabroom-2.tar.bz2
		filename="hourly-tabroom-1.tar.bz2"
	fi

	echo "Removing previous backup files"
	rm -r /backups/latest-tabroom

	echo "Performing hotbackup"
	/usr/bin/xtrabackup --backup --databases="tabroom"
	/usr/bin/xtrabackup --prepare --export --databases="tabroom"

	echo "Compressing backup data"
	cd /backups
	tar jcvf /home/s3/backups/latest-tabroom.tar.bz2 latest-tabroom
	cp /home/s3/backups/latest-tabroom.tar.bz2 latest-tabroom /home/s3/backups/${filename} 
	echo "All set!"
fi
