#!/bin/bash

hostname=`hostname -s`
prodserver='athena'

if [[ ${hostname} != ${prodserver} ]]; then

	rm /tmp/tabroom.sql

	echo "Accessing latest data dump"

	s3cmd get s3://nsda-backups/00-latest/db/tabroom.sql.bz2  /tmp/testing-tabroom.sql.bz2

	echo "Decompressing data dump"

	bunzip2 /tmp/testing-tabroom.sql.bz2

	echo "Dropping old database"

	mysqladmin -u root -f drop tabroom_testing

	echo "Creating new blank database"

	mysqladmin -u root create tabroom_testing

	echo "Loading datafile"

	pv /tmp/testing-tabroom.sql | mysql -u root -f tabroom_testing

	echo "Loading tables with external views on Tabroom"

	mysql -u root -f tabroom_testing < /www/tabroom/doc/convert/calendar.sql

	echo "Setting up the node.js views"
	mysql -u root -f tabroom_testing < /www/tabroom/doc/tabroom-api-view.sql

	echo "Removing data dump"
	rm /tmp/testing-tabroom.sql

	echo "All set!"

fi

